In [1]:
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr

import cloud_identification

In [3]:
l = 100.
N = 300

dx = l/N

x_ = np.linspace(-l/2., l/2., N)
y_ = np.linspace(-l/2., l/2., N)
z_ = np.linspace(-l/2., l/2., N)

ds = xr.Dataset(coords=dict(x=x_, y=y_, z=z_))

ds['r'] = np.sqrt(ds.x**2. + ds.y**2. + ds.z**2.)

lr = 0.3*ds.r.max()

ds['mask'] = ds.r < lr

labels = cloud_identification.number_objects(mask=ds.mask, scalar_field=ds.r)

ds['labels'] = (ds.r.dims, labels)

In [4]:
scales_cpp = cloud_identification.topological_scales(ds.labels, dx=dx)
scales_cpp

array([[26.000002],
       [25.774963],
       [25.90437 ],
       [ 0.5     ]], dtype=float32)

In [5]:
import genesis.objects.minkowski_scales

In [9]:
ds_scales = genesis.objects.minkowski_scales.main(ds.labels.rename(dict(x='xt', y='yt', z='zt')))
ds_scales

<xarray.Dataset>
Dimensions:        (object_id: 1)
Coordinates:
  * object_id      (object_id) int64 1
Data variables:
    length         (object_id) float32 26.086956
    width          (object_id) float32 25.861164
    thickness      (object_id) float32 25.991007
    genus          (object_id) float32 0.5
    planarity      (object_id) float32 -0.0025040947
    filamentarity  (object_id) float32 0.004346489
    volume         (object_id) float64 7.345e+04
    num_cells      (object_id) int32 1963344

In [10]:
V_scales = ds_scales.length*ds_scales.width*ds_scales.thickness

In [11]:
V_scales/ds_scales.volume

<xarray.DataArray (object_id: 1)>
array([0.238733])
Coordinates:
  * object_id  (object_id) int64 1

In [13]:
V = 4./3.*3.14*lr**3.
V/ds_scales.volume

<xarray.DataArray (object_id: 1)>
array([0.999634])
Coordinates:
  * object_id  (object_id) int64 1